#!/bin/bash
#
# Copyright (C) 2006 - 2014 FOSS-Group
#                    Germany
#                    http://www.foss-group.de
#                    support@foss-group.de
# Authors:
# Beat Stebler <beat.stebler@foss-group.ch>
#  
# Licensed under the EUPL, Version 1.1 or higher as soon they
# will be approved by the European Commission - subsequent
# versions of the EUPL (the "Licence"); You may not use this
# work except in compliance with the Licence.
# 
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in
# writing, software distributed under the Licence is
# distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.
# See the Licence for the specific language governing
# permissions and limitations under the Licence.
#

######################################################################################################
# Description:
#   Check variables of user entered with the call of this script
#   autobuild.sh pre  or autobuild.sh final
######################################################################################################

######################################################################################################
# Variables
######################################################################################################

# current folder 
currentPwd=$(pwd)

updateMode=$1

######################################################################################################
# FOSS-Cloud logo
######################################################################################################

logoFOSS-Cloud ()  {
clear

cat << \EOF >&1

                     __________  __________       ________                __
                    / ____/ __ \/ ___/ ___/      / ____/ /___  __  ______/ /
                   / /_  / / / /\__ \\__ \______/ /   / / __ \/ / / / __  /
                  / __/ / /_/ /___/ /__/ /_____/ /___/ / /_/ / /_/ / /_/ /
                 /_/    \____//____/____/      \____/_/\____/\__,_/\__,_/
EOF
}


######################################################################################################
# Check if entry is ok
######################################################################################################

if [ $updateMode == "--hard" -o $updateMode == "--sync" ] ; then
    echo ""
  else
    logoFOSS-Cloud
    echo ""
    echo ""
    echo "-----------------------------------------------------------------------------------------------"
    echo "   Please use this script as followed:"
    echo "-----------------------------------------------------------------------------------------------"
    echo ""
    echo "   $0 --sync"
    echo ""
    echo "          - This will do a synchronization of your portage tree and portage overlay."
    echo ""
    echo "   $0 --hard"
    echo ""
    echo "          - This will do a hard reset of your portage tree and portage overlay."
    echo "            Use --hard only, when --sync do not work."
    echo ""
    echo "-----------------------------------------------------------------------------------------------"
    echo ""
    exit
fi


######################################################################################################
# Update portage and Overlay
######################################################################################################


logoFOSS-Cloud
echo ""
echo "-----------------------------------------------------------------------------------------------"
echo "   Updating portage and portage-overlays..."
echo "-----------------------------------------------------------------------------------------------"
echo ""

if [[ $updateMode == "--hard" ]] ; then
    
    # Check branch on portage
    echo "RUN       : Check portage branch"
    cd /usr/portage/
    portageBranch=$(git status | grep branch -m 1 | cut -d " " -f 3)

    # Check branch on portage overlay
    echo "RUN       : Check portage-overlay branch"
    cd /var/lib/layman/foss-cloud/
    portageOverlayBranch=$(git status | grep branch -m 1 | cut -d " " -f 3)

    echo "RUN       : Reset portage-overlay foss-cloud"
    cd /var/lib/layman/

    # Remove the portage overlay
    rm -rf foss-cloud

    # Clone portage overlay from github
    git clone https://github.com/FOSS-Cloud/fc-portage-overlay.git

    # Rename the folder
    mv fc-portage-overlay foss-cloud
    
    # Set branch as before
    echo "RUN       : Checkout branch on portage-overlay" 
    cd /var/lib/layman/foss-cloud
    git checkout $portageOverlayBranch

    cd /usr

    # Remove portage
    echo "INFO      : Following mesage can be ignored"
    rm -rf /usr/portage

    echo "RUN       : Reset portage"

    # Clone porgage from github
    git clone https://github.com/FOSS-Cloud/portage.git

    # Set branch as before
    echo "RUN       : Checkout branch on portage" 
    cd /usr/portage/
    git checkout $portageBranch

    # Update DB portage-overlay
    echo "RUN       : Update DB portage-overlay"
    layman -s foss-cloud

    # Set permission on portage-overlay
    echo "RUN       : Setting permission portage-overlay" 
    chmod 2755 /var/lib/layman/foss-cloud
    chmod -R 755 /var/lib/layman/foss-cloud/
    chown -R portage:portage /var/lib/layman/foss-cloud/

    # Set permission on porgage
    echo "RUN       : Setting permission portage" 
    chmod 2755 /usr/portage
    chmod -R 755 /usr/portage/
    chown -R portage:portage /usr/portage/
    echo ""

  else

    # If the script is running with --sync do just a sync
    emerge --sync
fi

# Delete news
eselect news read all &>/dev/null

# Go back to the folder before
cd $currentPwd
echo "-----------------------------------------------------------------------------------------------"
echo ""
