#!/bin/bash
#
# Copyright (C) 2015 FOSS-Group GmbH
#                    Germany
#                    http://www.foss-group.de
#                    support@foss-group.de
#
# Authors:
# Beat Stebler <beat.stebler@foss-group.ch>
#
# Licensed under the EUPL, Version 1.1 or higher
# URL: https://joinup.ec.europa.eu/software/page/eupl
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#

######################################################################################################
# Function license
######################################################################################################

function license () {

cat << \EOF >&1

Copyright (C) 2015 FOSS-Group GmbH 
                   Germany
                   http://www.foss-group.de
                   support@foss-group.de

Authors:
Beat Stebler <beat.stebler@foss-group.ch>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

EOF
}

######################################################################################################
# Description:
#   Check variables of user entered with the call of this script
#   autobuild.sh pre  or autobuild.sh final
######################################################################################################

logoFOSS-Cloud ()  {
clear

cat << \EOF >&1

                     __________  __________       ________                __
                    / ____/ __ \/ ___/ ___/      / ____/ /___  __  ______/ /
                   / /_  / / / /\__ \\__ \______/ /   / / __ \/ / / / __  /
                  / __/ / /_/ /___/ /__/ /_____/ /___/ / /_/ / /_/ / /_/ /
                 /_/    \____//____/____/      \____/_/\____/\__,_/\__,_/
EOF
}

######################################################################################################
# Variables
######################################################################################################

# Get the current date and store in the variable CURRENT_DATE in the form of "2015-11-28".
CURRENT_DATE=`date +%Y-%m-%d`

# Get the current date and store in the variable DATE in the form of "Son Nov 29 10:03:01 CET 2015".
DATE="[$(date)]"

# Get the fully qualified domain name (HOST) and store it in the variable HOST in the form of <hostname>.<domain>.tld
FQDN=`hostname --fqdn`

# Get the hostname and store it in the variable HOST the form of <hostname>.
HOST=`hostname`

# Set option attribute and argument out of the command line
OPTION="$1"
ATTRIBUTE="$2"
ARGUMENT=$(echo $3 | sed 's:/$::')

# Define screen variables
CHECK="FC-CHECK   : "
WARNING="FC-WARNING : "
RUN="FC-RUN     : "
INFO="FC-INFO    : "
ERROR="FC-ERROR   : "

# Define line
titleLine="**********************************************************************************"

# Define Graphic
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
VIOLET=$(tput setaf 5)
LIGHTBLUE=$(tput setaf 6)
BOLD=$(tput bold)
UNDERLINE=$(tput sgr 0 1)
NORMAL=$(tput sgr0)



if [[ "$1" = "--license" ]] ; then
	license
fi
	
logoFOSS-Cloud
echo ""
echo "-----------------------------------------------------------------------------------------------"
echo "   Setting permission. Please be patient..."
echo "-----------------------------------------------------------------------------------------------"
echo ""
echo "   RUN       : Setting permission portage-overlay" 
chmod 2755 /var/lib/layman/foss-cloud
chmod -R 755 /var/lib/layman/foss-cloud/
chown -R portage:portage /var/lib/layman/foss-cloud/

echo "   RUN       : Setting permission portage" 
chmod 2755 /usr/portage
chmod -R 755 /usr/portage/
chown -R portage:portage /usr/portage/

echo "   RUN       : Setting permission /var/virtualization" 
chown -R root:vm-storage /var/virtualization
chmod -R 644 /var/virtualization/iso
chmod -R 644 /var/virtualization/iso-choosable
chmod -R 664 /var/virtualization/vm-templates
chmod -R 664 /var/virtualization/vm-dynamic
chmod -R 664 /var/virtualization/vm-persistent
chmod -R 664 /var/virtualization/tmp
chmod -R 664 /var/virtualization/backup

cd /var/virtualization/
chmod 0770 *
cd /var/virtualization/iso/
chmod 0770 *
cd /var/virtualization/iso-choosable/
chmod 0770 *
cd /var/virtualization/vm-templates/
chmod 0770 *
cd /var/virtualization/vm-dynamic/
chmod 0770 *
cd /var/virtualization/vm-persistent/
chmod 0770 *
cd /var/virtualization/backup/
chmod 0770 *
cd /var/virtualization/tmp/
chmod 0770 *

echo "   RUN       : Setting permission /usr/local"
chmod  0755 /usr/local/
chmod -R 755 /usr/local/

echo "   RUN       : Setting permission /var/www/localhost/htdocs/vm-manager/protected/runtime/"
chmod -R 770 /var/www/localhost/htdocs/vm-manager/protected/runtime/
chown -R root:apache /var/www/localhost/htdocs/vm-manager/protected/runtime/
chmod 770 /var/www/localhost/htdocs/vm-manager/protected/runtime
chown apache:apache /var/www/localhost/htdocs/vm-manager/protected/runtime
chmod 770 /var/www/localhost/htdocs/vm-manager/protected/runtime/cron
chmod 644 /var/www/localhost/htdocs/vm-manager/protected/runtime/cron/*
chown apache:apache /var/www/localhost/htdocs/vm-manager/protected/runtime/cron
chmod 770 /var/www/localhost/htdocs/vm-manager/protected/runtime/patches
chown root:apache /var/www/localhost/htdocs/vm-manager/protected/runtime/patches
if [ -e "/var/www/localhost/htdocs/vm-manager/protected/runtime/patches/archive" ] ; then
    chmod 770 /var/www/localhost/htdocs/vm-manager/protected/runtime/patches/archive
    chown root:apache /var/www/localhost/htdocs/vm-manager/protected/runtime/patches/archive
fi

cd ${currentPwd}

echo ""
echo "-----------------------------------------------------------------------------------------------"
echo "   Permission are set now"
echo "-----------------------------------------------------------------------------------------------"

